# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.DateField(auto_now=True),
        ),
    ]
