# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170531_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
    ]
